
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT


def connect_db():

    return psycopg2.connect(
        host='localhost',
        port='5434',
        database='proposalagentchatdb',
        user='postgres',
        password='Deadpool@123'
    )


def create_schema():

    conn = None
    cur = None

    try:
        # Connect to database
        conn = connect_db()
        conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        cur = conn.cursor()

        print("Connected to PostgreSQL database")

        # Drop existing table if needed (for clean setup)
        print("Setting up embeddings table...")
        cur.execute("DROP TABLE IF EXISTS embeddings CASCADE")

        # Create embeddings table following pgvectorscale schema
        # Using 768 dimensions for nomic-embed-text
        create_table_sql = """
        CREATE TABLE IF NOT EXISTS embeddings (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            metadata JSONB,
            contents TEXT,
            embedding VECTOR(768)
        )
        """

        cur.execute(create_table_sql)
        print("✓ Embeddings table created successfully")

        # Create indexes for better performance
        print("Creating indexes...")

        # Create GIN index for full-text search on contents
        cur.execute("""
            CREATE INDEX IF NOT EXISTS embeddings_contents_gin_idx 
            ON embeddings 
            USING gin(to_tsvector('english', contents))
        """)
        print("✓ GIN index for full-text search created")

        # Create vector index for similarity search

        try:
            cur.execute("""
                CREATE INDEX IF NOT EXISTS embeddings_embedding_idx 
                ON embeddings 
                USING diskann (embedding vector_cosine_ops)
            """)
            print("✓ StreamingDiskANN index created (pgvectorscale)")
        except psycopg2.Error:
            # Fallback to HNSW index if pgvectorscale not available
            cur.execute("""
                CREATE INDEX IF NOT EXISTS embeddings_embedding_idx 
                ON embeddings 
                USING hnsw (embedding vector_cosine_ops)
                WITH (m = 16, ef_construction = 64)
            """)
            print("✓ HNSW index created (pgvector)")

        # Verify table structure
        cur.execute("""
            SELECT column_name, data_type 
            FROM information_schema.columns 
            WHERE table_name = 'embeddings'
            ORDER BY ordinal_position
        """)

        columns = cur.fetchall()
        print("\nTable structure:")
        for col_name, col_type in columns:
            print(f"  - {col_name}: {col_type}")

        # Verify indexes
        cur.execute("""
            SELECT indexname, indexdef 
            FROM pg_indexes 
            WHERE tablename = 'embeddings'
        """)

        indexes = cur.fetchall()
        print("\nCreated indexes:")
        for idx_name, idx_def in indexes:
            print(f"  - {idx_name}")

        print("\n✅ Database schema created successfully!")

    except psycopg2.Error as e:
        print(f"❌ Database error: {e}")
        raise
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        raise
    finally:
        if cur:
            cur.close()
        if conn:
            conn.close()


if __name__ == "__main__":
    create_schema()